language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install nose flake8
  - pip install .
script:
  - flake8
  - nosetests -vv test.py
